### PR TITLE
emacs keybind for reloading server

### PR DESCRIPTION
**Pull request by tommy-mor**
@awkay in one of your fulcro videos, you said you had a bind in intellij to reload the server. this file adds that bind for emacs users.

Not suggesting you merge this, putting this here more as documentation for people who might want to use it.

### CODE REVIEW

**Comment by awkay** [comment]
I don't leave open MRs on repositories. I can merge it, or you can proffer this suggestion up in the developer guide for merging there. Documentation should be in documentation :D

**Comment by tommy-mor** [comment]
what about putting the snippet as a comment right here? https://github.com/fulcrologic/fulcro-template/blob/f3c607d4253ea71087dd5c7e8031f0c191017e26/src/dev/user.clj#L15

doesnt seem like the developer guide has a good section for editor tweaks.

**Comment by awkay** [comment]
sure.

**Comment by tommy-mor** [comment]
done :+1:

**Comment by awkay** [comment]
cool

**Pull request merged**
